-- Generated by EDG cpfe-lean from /home/claude/amd.c/laws/ie_laws.cpp.
-- Do not edit: run the translation again.

namespace C

/-- C++ unsigned int -/
abbrev U32 := BitVec 32

/-- lean::Mem and lean::Ram (include/lean_mem.h): an array of unsigned
int.  Here it is any function from U32 to U32, so a theorem with a Mem
parameter holds for every array content. -/
structure Mem where
  get : U32 -> U32

/-- C++: lean::load(m, i), that is m.p[i] -/
def Mem.load (m : Mem) (i : U32) : U32 := m.get i

/-- C++: lean::ram_store(m, i, v): a new memory with v at i -/
def Mem.store (m : Mem) (i v : U32) : Mem :=
  Mem.mk (fun j => bif j == i then v else m.get j)

/-- C++: struct Plan -/
structure Plan where
  off : Mem
  size : Mem
  first : Mem
  last : Mem
  n : U32
  cap : U32

/-- C++: ie_wave -/
def ie_wave : U32 :=
  32#32

/-- C++: ie_rows_per_wg -/
def ie_rows_per_wg : U32 :=
  8#32

/-- C++: ie_align_mask -/
def ie_align_mask : U32 :=
  255#32

/-- C++: ie_sizes_ok -/
def ie_sizes_ok (rows : U32) (nb : U32) : Bool :=
  ((BitVec.ult rows 262144#32) && (BitVec.ult nb 512#32))

/-- C++: ie_q4_src_blk -/
def ie_q4_src_blk (r : U32) (b : U32) (nb : U32) : U32 :=
  (((r * nb) + b) * 18#32)

/-- C++: ie_q4_src_qbyte -/
def ie_q4_src_qbyte (r : U32) (b : U32) (k : U32) (nb : U32) : U32 :=
  (((((r * nb) + b) * 18#32) + 2#32) + k)

/-- C++: ie_q4_dst_word -/
def ie_q4_dst_word (r : U32) (b : U32) (w : U32) (nb : U32) : U32 :=
  ((((r * nb) + b) * 4#32) + w)

/-- C++: ie_q4_dst_scale -/
def ie_q4_dst_scale (r : U32) (b : U32) (nb : U32) : U32 :=
  ((r * nb) + b)

/-- C++: ie_q4_word_row -/
def ie_q4_word_row (i : U32) (nb : U32) : U32 :=
  ((i / 4#32) / nb)

/-- C++: ie_q4_word_blk -/
def ie_q4_word_blk (i : U32) (nb : U32) : U32 :=
  ((i / 4#32) % nb)

/-- C++: ie_q4_word_w -/
def ie_q4_word_w (i : U32) : U32 :=
  (i % 4#32)

/-- C++: ie_byte -/
def ie_byte (x : U32) (e : U32) : U32 :=
  ((x >>> (8#32 * e)) &&& 255#32)

/-- C++: ie_pack4 -/
def ie_pack4 (b0 : U32) (b1 : U32) (b2 : U32) (b3 : U32) : U32 :=
  ((((b0 &&& 255#32) ||| ((b1 &&& 255#32) <<< 8)) ||| ((b2 &&& 255#32) <<< 16)) ||| ((b3 &&& 255#32) <<< 24))

/-- C++: ie_q4_word_of -/
def ie_q4_word_of (j : U32) : U32 :=
  ((j &&& 15#32) >>> 2)

/-- C++: ie_q4_nib -/
def ie_q4_nib (word : U32) (j : U32) : U32 :=
  ((word >>> ((8#32 * (j &&& 3#32)) + (4#32 * ((j >>> 4) &&& 1#32)))) &&& 15#32)

/-- C++: ie_q4_spec_nib -/
def ie_q4_spec_nib (qbyte : U32) (j : U32) : U32 :=
  (bif (BitVec.ult j 16#32) then (qbyte &&& 15#32) else ((qbyte &&& 255#32) >>> 4))

/-- C++: ie_sext8 -/
def ie_sext8 (v : U32) : U32 :=
  (bif ((v &&& 128#32) != 0#32) then ((v &&& 255#32) ||| 4294967040#32) else (v &&& 255#32))

/-- C++: ie_dot4_us -/
def ie_dot4_us (acc : U32) (a : U32) (b : U32) : U32 :=
  ((((acc + ((ie_byte a 0#32) * (ie_sext8 (ie_byte b 0#32)))) + ((ie_byte a 1#32) * (ie_sext8 (ie_byte b 1#32)))) + ((ie_byte a 2#32) * (ie_sext8 (ie_byte b 2#32)))) + ((ie_byte a 3#32) * (ie_sext8 (ie_byte b 3#32))))

/-- C++: ie_sum_s8x4 -/
def ie_sum_s8x4 (a : U32) : U32 :=
  ((((ie_sext8 (ie_byte a 0#32)) + (ie_sext8 (ie_byte a 1#32))) + (ie_sext8 (ie_byte a 2#32))) + (ie_sext8 (ie_byte a 3#32)))

/-- C++: ie_q4q8_word -/
def ie_q4q8_word (acc : U32) (wq : U32) (alo : U32) (ahi : U32) : U32 :=
  (ie_dot4_us (ie_dot4_us acc (wq &&& 252645135#32) alo) ((wq >>> 4) &&& 252645135#32) ahi)

/-- C++: ie_q4q8_word_spec -/
def ie_q4q8_word_spec (wq : U32) (alo : U32) (ahi : U32) : U32 :=
  ((((((((((ie_q4_nib wq 0#32) - 8#32) * (ie_sext8 (ie_byte alo 0#32))) + (((ie_q4_nib wq 1#32) - 8#32) * (ie_sext8 (ie_byte alo 1#32)))) + (((ie_q4_nib wq 2#32) - 8#32) * (ie_sext8 (ie_byte alo 2#32)))) + (((ie_q4_nib wq 3#32) - 8#32) * (ie_sext8 (ie_byte alo 3#32)))) + (((ie_q4_nib wq 16#32) - 8#32) * (ie_sext8 (ie_byte ahi 0#32)))) + (((ie_q4_nib wq 17#32) - 8#32) * (ie_sext8 (ie_byte ahi 1#32)))) + (((ie_q4_nib wq 18#32) - 8#32) * (ie_sext8 (ie_byte ahi 2#32)))) + (((ie_q4_nib wq 19#32) - 8#32) * (ie_sext8 (ie_byte ahi 3#32))))

/-- C++: ie_q8_sum -/
def ie_q8_sum (aw : Mem) (ab : U32) : U32 :=
  ((((((((ie_sum_s8x4 (Mem.load aw ab)) + (ie_sum_s8x4 (Mem.load aw (ab + 1#32)))) + (ie_sum_s8x4 (Mem.load aw (ab + 2#32)))) + (ie_sum_s8x4 (Mem.load aw (ab + 3#32)))) + (ie_sum_s8x4 (Mem.load aw (ab + 4#32)))) + (ie_sum_s8x4 (Mem.load aw (ab + 5#32)))) + (ie_sum_s8x4 (Mem.load aw (ab + 6#32)))) + (ie_sum_s8x4 (Mem.load aw (ab + 7#32))))

/-- C++: ie_q4q8_block -/
def ie_q4q8_block (qw : Mem) (qb : U32) (aw : Mem) (ab : U32) (asum : U32) : U32 :=
  ((ie_q4q8_word (ie_q4q8_word (ie_q4q8_word (ie_q4q8_word 0#32 (Mem.load qw qb) (Mem.load aw ab) (Mem.load aw (ab + 4#32))) (Mem.load qw (qb + 1#32)) (Mem.load aw (ab + 1#32)) (Mem.load aw (ab + 5#32))) (Mem.load qw (qb + 2#32)) (Mem.load aw (ab + 2#32)) (Mem.load aw (ab + 6#32))) (Mem.load qw (qb + 3#32)) (Mem.load aw (ab + 3#32)) (Mem.load aw (ab + 7#32))) - (8#32 * asum))

/-- C++: ie_q4q8_term -/
def ie_q4q8_term (qw : Mem) (qb : U32) (aw : Mem) (ab : U32) (j : U32) : U32 :=
  (((ie_q4_nib (Mem.load qw (qb + (ie_q4_word_of j))) j) - 8#32) * (ie_sext8 (ie_byte (Mem.load aw (ab + (j >>> 2))) (j &&& 3#32))))

/-- C++: ie_q4q8_spec (recursive: fuel counts down with n) -/
def ie_q4q8_spec.go (fuel : Nat) (n : U32) (qw : Mem) (qb : U32) (aw : Mem) (ab : U32) (j : U32) : U32 :=
  match fuel with
  | 0 =>
    0#32
  | fuel' + 1 =>
    (bif (BitVec.ult j 32#32) then ((ie_q4q8_term qw qb aw ab j) + (ie_q4q8_spec.go fuel' (n - 1#32) qw qb aw ab (j + 1#32))) else 0#32)

/-- C++: ie_q4q8_spec -/
def ie_q4q8_spec (n : U32) (qw : Mem) (qb : U32) (aw : Mem) (ab : U32) (j : U32) : U32 :=
  ie_q4q8_spec.go n.toNat n qw qb aw ab j

/-- C++: ie_q8_sizes_ok -/
def ie_q8_sizes_ok (rows : U32) (nb : U32) : Bool :=
  (((BitVec.ult rows 262144#32) && (BitVec.ult nb 2048#32)) && (BitVec.ult (rows * nb) 67108864#32))

/-- C++: ie_q8_src_blk -/
def ie_q8_src_blk (r : U32) (b : U32) (nb : U32) : U32 :=
  (((r * nb) + b) * 34#32)

/-- C++: ie_q8_src_qbyte -/
def ie_q8_src_qbyte (r : U32) (b : U32) (k : U32) (nb : U32) : U32 :=
  (((((r * nb) + b) * 34#32) + 2#32) + k)

/-- C++: ie_q8_dst_word -/
def ie_q8_dst_word (r : U32) (b : U32) (w : U32) (nb : U32) : U32 :=
  ((((r * nb) + b) * 8#32) + w)

/-- C++: ie_q8_dst_scale -/
def ie_q8_dst_scale (r : U32) (b : U32) (nb : U32) : U32 :=
  ((r * nb) + b)

/-- C++: ie_q8_word_row -/
def ie_q8_word_row (i : U32) (nb : U32) : U32 :=
  ((i / 8#32) / nb)

/-- C++: ie_q8_word_blk -/
def ie_q8_word_blk (i : U32) (nb : U32) : U32 :=
  ((i / 8#32) % nb)

/-- C++: ie_q8_word_w -/
def ie_q8_word_w (i : U32) : U32 :=
  (i % 8#32)

/-- C++: ie_dot4_ss -/
def ie_dot4_ss (acc : U32) (a : U32) (b : U32) : U32 :=
  ((((acc + ((ie_sext8 (ie_byte a 0#32)) * (ie_sext8 (ie_byte b 0#32)))) + ((ie_sext8 (ie_byte a 1#32)) * (ie_sext8 (ie_byte b 1#32)))) + ((ie_sext8 (ie_byte a 2#32)) * (ie_sext8 (ie_byte b 2#32)))) + ((ie_sext8 (ie_byte a 3#32)) * (ie_sext8 (ie_byte b 3#32))))

/-- C++: ie_q8q8_block -/
def ie_q8q8_block (qw : Mem) (qb : U32) (aw : Mem) (ab : U32) : U32 :=
  (ie_dot4_ss (ie_dot4_ss (ie_dot4_ss (ie_dot4_ss (ie_dot4_ss (ie_dot4_ss (ie_dot4_ss (ie_dot4_ss 0#32 (Mem.load qw qb) (Mem.load aw ab)) (Mem.load qw (qb + 1#32)) (Mem.load aw (ab + 1#32))) (Mem.load qw (qb + 2#32)) (Mem.load aw (ab + 2#32))) (Mem.load qw (qb + 3#32)) (Mem.load aw (ab + 3#32))) (Mem.load qw (qb + 4#32)) (Mem.load aw (ab + 4#32))) (Mem.load qw (qb + 5#32)) (Mem.load aw (ab + 5#32))) (Mem.load qw (qb + 6#32)) (Mem.load aw (ab + 6#32))) (Mem.load qw (qb + 7#32)) (Mem.load aw (ab + 7#32)))

/-- C++: ie_q8q8_term -/
def ie_q8q8_term (qw : Mem) (qb : U32) (aw : Mem) (ab : U32) (j : U32) : U32 :=
  ((ie_sext8 (ie_byte (Mem.load qw (qb + (j >>> 2))) (j &&& 3#32))) * (ie_sext8 (ie_byte (Mem.load aw (ab + (j >>> 2))) (j &&& 3#32))))

/-- C++: ie_q8q8_spec (recursive: fuel counts down with n) -/
def ie_q8q8_spec.go (fuel : Nat) (n : U32) (qw : Mem) (qb : U32) (aw : Mem) (ab : U32) (j : U32) : U32 :=
  match fuel with
  | 0 =>
    0#32
  | fuel' + 1 =>
    (bif (BitVec.ult j 32#32) then ((ie_q8q8_term qw qb aw ab j) + (ie_q8q8_spec.go fuel' (n - 1#32) qw qb aw ab (j + 1#32))) else 0#32)

/-- C++: ie_q8q8_spec -/
def ie_q8q8_spec (n : U32) (qw : Mem) (qb : U32) (aw : Mem) (ab : U32) (j : U32) : U32 :=
  ie_q8q8_spec.go n.toNat n qw qb aw ab j

/-- C++: ie_q4k_sizes_ok -/
def ie_q4k_sizes_ok (rows : U32) (nb : U32) : Bool :=
  ((((BitVec.ult rows 262144#32) && (BitVec.ult nb 2048#32)) && (BitVec.ult (rows * nb) 67108864#32)) && ((nb % 8#32) == 0#32))

/-- C++: ie_q4k_sm -/
def ie_q4k_sm (r : U32) (b : U32) (nb : U32) : U32 :=
  ((r * nb) + b)

/-- C++: ie_q4k_dd -/
def ie_q4k_dd (rows : U32) (r : U32) (b : U32) (nb : U32) : U32 :=
  ((rows * nb) + (((r * (nb / 8#32)) + (b / 8#32)) * 2#32))

/-- C++: ie_q4k_qs_n -/
def ie_q4k_qs_n (rows : U32) (nb : U32) : U32 :=
  ((rows * nb) + ((rows * (nb / 8#32)) * 2#32))

/-- C++: ie_q4k_src_blk -/
def ie_q4k_src_blk (r : U32) (b : U32) (nb : U32) : U32 :=
  (((r * nb) + ((b / 8#32) * 8#32)) * 18#32)

/-- C++: ie_q4k_src_qbyte -/
def ie_q4k_src_qbyte (r : U32) (b : U32) (j : U32) (nb : U32) : U32 :=
  ((((ie_q4k_src_blk r b nb) + 16#32) + (32#32 * ((b % 8#32) / 2#32))) + j)

/-- C++: ie_q4k_src_nib -/
def ie_q4k_src_nib (qbyte : U32) (b : U32) : U32 :=
  (bif ((b % 2#32) == 1#32) then ((qbyte &&& 255#32) >>> 4) else (qbyte &&& 15#32))

/-- C++: ie_q4k_pack -/
def ie_q4k_pack (lo : U32) (hi : U32) (b : U32) : U32 :=
  ((ie_q4k_src_nib lo b) ||| ((ie_q4k_src_nib hi b) <<< 4))

/-- C++: ie_q4k_dot -/
def ie_q4k_dot (qw : Mem) (qb : U32) (aw : Mem) (ab : U32) : U32 :=
  (ie_q4q8_word (ie_q4q8_word (ie_q4q8_word (ie_q4q8_word 0#32 (Mem.load qw qb) (Mem.load aw ab) (Mem.load aw (ab + 4#32))) (Mem.load qw (qb + 1#32)) (Mem.load aw (ab + 1#32)) (Mem.load aw (ab + 5#32))) (Mem.load qw (qb + 2#32)) (Mem.load aw (ab + 2#32)) (Mem.load aw (ab + 6#32))) (Mem.load qw (qb + 3#32)) (Mem.load aw (ab + 3#32)) (Mem.load aw (ab + 7#32)))

/-- C++: ie_q4k_term -/
def ie_q4k_term (qw : Mem) (qb : U32) (aw : Mem) (ab : U32) (j : U32) : U32 :=
  ((ie_q4_nib (Mem.load qw (qb + (ie_q4_word_of j))) j) * (ie_sext8 (ie_byte (Mem.load aw (ab + (j >>> 2))) (j &&& 3#32))))

/-- C++: ie_q4k_spec (recursive: fuel counts down with n) -/
def ie_q4k_spec.go (fuel : Nat) (n : U32) (qw : Mem) (qb : U32) (aw : Mem) (ab : U32) (j : U32) : U32 :=
  match fuel with
  | 0 =>
    0#32
  | fuel' + 1 =>
    (bif (BitVec.ult j 32#32) then ((ie_q4k_term qw qb aw ab j) + (ie_q4k_spec.go fuel' (n - 1#32) qw qb aw ab (j + 1#32))) else 0#32)

/-- C++: ie_q4k_spec -/
def ie_q4k_spec (n : U32) (qw : Mem) (qb : U32) (aw : Mem) (ab : U32) (j : U32) : U32 :=
  ie_q4k_spec.go n.toNat n qw qb aw ab j

/-- C++: ie_gemv_ngroups -/
def ie_gemv_ngroups (rows : U32) : U32 :=
  ((rows + 7#32) >>> 3)

/-- C++: ie_gemv_row -/
def ie_gemv_row (g : U32) (v : U32) : U32 :=
  ((g * 8#32) + v)

/-- C++: ie_lane_blk -/
def ie_lane_blk (l : U32) (t : U32) : U32 :=
  (l + (32#32 * t))

/-- C++: ie_blk_lane -/
def ie_blk_lane (b : U32) : U32 :=
  (b &&& 31#32)

/-- C++: ie_blk_step -/
def ie_blk_step (b : U32) : U32 :=
  (b >>> 5)

/-- C++: ie_seq_sum (recursive: fuel counts down with n) -/
def ie_seq_sum.go (fuel : Nat) (n : U32) (x : Mem) (lo : U32) (hi : U32) : U32 :=
  match fuel with
  | 0 =>
    0#32
  | fuel' + 1 =>
    (bif (BitVec.ult lo hi) then ((Mem.load x lo) + (ie_seq_sum.go fuel' (n - 1#32) x (lo + 1#32) hi)) else 0#32)

/-- C++: ie_seq_sum -/
def ie_seq_sum (n : U32) (x : Mem) (lo : U32) (hi : U32) : U32 :=
  ie_seq_sum.go n.toNat n x lo hi

/-- C++: ie_lane_sum (recursive: fuel counts down with n) -/
def ie_lane_sum.go (fuel : Nat) (n : U32) (x : Mem) (b : U32) (nb : U32) : U32 :=
  match fuel with
  | 0 =>
    0#32
  | fuel' + 1 =>
    (bif (BitVec.ult b nb) then ((Mem.load x b) + (ie_lane_sum.go fuel' (n - 1#32) x (b + 32#32) nb)) else 0#32)

/-- C++: ie_lane_sum -/
def ie_lane_sum (n : U32) (x : Mem) (b : U32) (nb : U32) : U32 :=
  ie_lane_sum.go n.toNat n x b nb

/-- C++: ie_lanes_sum (recursive: fuel counts down with n) -/
def ie_lanes_sum.go (fuel : Nat) (n : U32) (x : Mem) (l : U32) (nb : U32) : U32 :=
  match fuel with
  | 0 =>
    0#32
  | fuel' + 1 =>
    (bif (BitVec.ult l 32#32) then ((ie_lane_sum nb x l nb) + (ie_lanes_sum.go fuel' (n - 1#32) x (l + 1#32) nb)) else 0#32)

/-- C++: ie_lanes_sum -/
def ie_lanes_sum (n : U32) (x : Mem) (l : U32) (nb : U32) : U32 :=
  ie_lanes_sum.go n.toNat n x l nb

/-- C++: ie_strided_sum -/
def ie_strided_sum (x : Mem) (nb : U32) : U32 :=
  (ie_lanes_sum 32#32 x 0#32 nb)

/-- C++: ie_tree (recursive: fuel counts down with m) -/
def ie_tree.go (fuel : Nat) (m : U32) (x : Mem) (i : U32) : U32 :=
  match fuel with
  | 0 =>
    (Mem.load x i)
  | fuel' + 1 =>
    ((ie_tree.go fuel' (m - 1#32) x i) + (ie_tree.go fuel' (m - 1#32) x (i + (32#32 >>> m))))

/-- C++: ie_tree -/
def ie_tree (m : U32) (x : Mem) (i : U32) : U32 :=
  ie_tree.go m.toNat m x i

/-- C++: ie_wave_sum -/
def ie_wave_sum (x : Mem) : U32 :=
  (ie_tree 5#32 x 0#32)

/-- C++: ie_off -/
def ie_off (p : Plan) (i : U32) : U32 :=
  (Mem.load p.off i)

/-- C++: ie_size -/
def ie_size (p : Plan) (i : U32) : U32 :=
  (Mem.load p.size i)

/-- C++: ie_first -/
def ie_first (p : Plan) (i : U32) : U32 :=
  (Mem.load p.first i)

/-- C++: ie_last -/
def ie_last (p : Plan) (i : U32) : U32 :=
  (Mem.load p.last i)

/-- C++: ie_buf_ok -/
def ie_buf_ok (p : Plan) (i : U32) : Bool :=
  ((((BitVec.ule (ie_off p i) p.cap) && (BitVec.ule (ie_size p i) (p.cap - (ie_off p i)))) && (((ie_off p i) &&& ie_align_mask) == 0#32)) && (BitVec.ule (ie_first p i) (ie_last p i)))

/-- C++: ie_buf_sep -/
def ie_buf_sep (p : Plan) (i : U32) (j : U32) : Bool :=
  (((!((BitVec.ule (ie_first p i) (ie_last p j)) && (BitVec.ule (ie_first p j) (ie_last p i)))) || (BitVec.ule ((ie_off p i) + (ie_size p i)) (ie_off p j))) || (BitVec.ule ((ie_off p j) + (ie_size p j)) (ie_off p i)))

/-- C++: ie_pairs_ok (recursive: fuel counts down with k) -/
def ie_pairs_ok.go (fuel : Nat) (k : U32) (p : Plan) (i : U32) (j : U32) : Bool :=
  match fuel with
  | 0 =>
    true
  | fuel' + 1 =>
    (bif (BitVec.ult j p.n) then ((ie_buf_sep p i j) && (ie_pairs_ok.go fuel' (k - 1#32) p i (j + 1#32))) else true)

/-- C++: ie_pairs_ok -/
def ie_pairs_ok (k : U32) (p : Plan) (i : U32) (j : U32) : Bool :=
  ie_pairs_ok.go k.toNat k p i j

/-- C++: ie_bufs_ok (recursive: fuel counts down with k) -/
def ie_bufs_ok.go (fuel : Nat) (k : U32) (p : Plan) (i : U32) : Bool :=
  match fuel with
  | 0 =>
    true
  | fuel' + 1 =>
    (bif (BitVec.ult i p.n) then (((ie_buf_ok p i) && (ie_pairs_ok p.n p i (i + 1#32))) && (ie_bufs_ok.go fuel' (k - 1#32) p (i + 1#32))) else true)

/-- C++: ie_bufs_ok -/
def ie_bufs_ok (k : U32) (p : Plan) (i : U32) : Bool :=
  ie_bufs_ok.go k.toNat k p i

/-- C++: ie_plan_check -/
def ie_plan_check (p : Plan) : Bool :=
  (ie_bufs_ok p.n p 0#32)

/-- C++: ie_in_buf -/
def ie_in_buf (p : Plan) (i : U32) (x : U32) : Bool :=
  ((BitVec.ule (ie_off p i) x) && (BitVec.ult x ((ie_off p i) + (ie_size p i))))

/-- C++: ie_live -/
def ie_live (p : Plan) (i : U32) (t : U32) : Bool :=
  ((BitVec.ule (ie_first p i) t) && (BitVec.ule t (ie_last p i)))

/-- C++: law_grid_cover -/
def law_grid_cover (rows : U32) (r : U32) : Bool :=
  ((!((BitVec.ult rows 262144#32) && (BitVec.ult r rows))) || (((BitVec.ult (r >>> 3) (ie_gemv_ngroups rows)) && (BitVec.ult (r &&& 7#32) ie_rows_per_wg)) && ((ie_gemv_row (r >>> 3) (r &&& 7#32)) == r)))

/-- C++: law_grid_unique -/
def law_grid_unique (g : U32) (v : U32) (h : U32) (w : U32) : Bool :=
  ((!(((((BitVec.ult g 134217728#32) && (BitVec.ult h 134217728#32)) && (BitVec.ult v 8#32)) && (BitVec.ult w 8#32)) && ((ie_gemv_row g v) == (ie_gemv_row h w)))) || ((g == h) && (v == w)))

/-- C++: law_lane_cover -/
def law_lane_cover (b : U32) : Bool :=
  ((BitVec.ult (ie_blk_lane b) ie_wave) && ((ie_lane_blk (ie_blk_lane b) (ie_blk_step b)) == b))

/-- C++: law_lane_unique -/
def law_lane_unique (l : U32) (t : U32) (m : U32) (s : U32) : Bool :=
  ((!(((((BitVec.ult l 32#32) && (BitVec.ult m 32#32)) && (BitVec.ult t 67108864#32)) && (BitVec.ult s 67108864#32)) && ((ie_lane_blk l t) == (ie_lane_blk m s)))) || ((l == m) && (t == s)))

/-- C++: law_q4_addr -/
def law_q4_addr (rows : U32) (nb : U32) (r : U32) (b : U32) (w : U32) (k : U32) : Bool :=
  ((!(((((ie_sizes_ok rows nb) && (BitVec.ult r rows)) && (BitVec.ult b nb)) && (BitVec.ult w 4#32)) && (BitVec.ult k 16#32))) || ((((BitVec.ult (ie_q4_dst_word r b w nb) ((rows * nb) * 4#32)) && (BitVec.ult (ie_q4_dst_scale r b nb) (rows * nb))) && (BitVec.ult (ie_q4_src_qbyte r b k nb) ((rows * nb) * 18#32))) && (BitVec.ult ((ie_q4_src_blk r b nb) + 1#32) ((rows * nb) * 18#32))))

/-- C++: law_q4_inverse -/
def law_q4_inverse (rows : U32) (nb : U32) (r : U32) (b : U32) (w : U32) : Bool :=
  ((!((((ie_sizes_ok rows nb) && (BitVec.ult r rows)) && (BitVec.ult b nb)) && (BitVec.ult w 4#32))) || ((((ie_q4_word_row (ie_q4_dst_word r b w nb) nb) == r) && ((ie_q4_word_blk (ie_q4_dst_word r b w nb) nb) == b)) && ((ie_q4_word_w (ie_q4_dst_word r b w nb)) == w)))

/-- C++: law_q4_onto -/
def law_q4_onto (rows : U32) (nb : U32) (i : U32) : Bool :=
  ((!(((ie_sizes_ok rows nb) && (BitVec.ult 0#32 nb)) && (BitVec.ult i ((rows * nb) * 4#32)))) || (((BitVec.ult (ie_q4_word_row i nb) rows) && (BitVec.ult (ie_q4_word_blk i nb) nb)) && ((ie_q4_dst_word (ie_q4_word_row i nb) (ie_q4_word_blk i nb) (ie_q4_word_w i) nb) == i)))

/-- C++: law_act_addr -/
def law_act_addr (nb : U32) (b : U32) (v : U32) : Bool :=
  ((!(((BitVec.ult nb 2048#32) && (BitVec.ult b nb)) && (BitVec.ult v 8#32))) || (BitVec.ult ((b * 8#32) + v) (nb * 8#32)))

/-- C++: law_plan_fits -/
def law_plan_fits (p : Plan) (i : U32) (x : U32) : Bool :=
  ((!(((ie_plan_check p) && (BitVec.ult i p.n)) && (ie_in_buf p i x))) || (BitVec.ult x p.cap))

/-- C++: law_plan_aligned -/
def law_plan_aligned (p : Plan) (i : U32) : Bool :=
  ((!((ie_plan_check p) && (BitVec.ult i p.n))) || (((ie_off p i) &&& 255#32) == 0#32))

/-- C++: law_plan_no_clobber -/
def law_plan_no_clobber (p : Plan) (i : U32) (j : U32) (t : U32) (x : U32) : Bool :=
  ((!(((((((ie_plan_check p) && (BitVec.ult i p.n)) && (BitVec.ult j p.n)) && (i != j)) && (ie_live p i t)) && (ie_live p j t)) && (ie_in_buf p i x))) || (!(ie_in_buf p j x)))

/-- C++: law_strided_sum -/
def law_strided_sum (x : Mem) (nb : U32) : Bool :=
  ((!(BitVec.ult nb 1073741824#32)) || ((ie_strided_sum x nb) == (ie_seq_sum nb x 0#32 nb)))

/-- C++: law_wave_sum -/
def law_wave_sum (x : Mem) : Bool :=
  ((ie_wave_sum x) == (ie_seq_sum 32#32 x 0#32 32#32))

/-- C++: law_q4_nibble -/
def law_q4_nibble (q0 : U32) (q1 : U32) (q2 : U32) (q3 : U32) (j : U32) : Bool :=
  ((!(BitVec.ult j 32#32)) || ((ie_q4_nib (ie_pack4 q0 q1 q2 q3) j) == (ie_q4_spec_nib (bif ((j &&& 3#32) == 0#32) then q0 else (bif ((j &&& 3#32) == 1#32) then q1 else (bif ((j &&& 3#32) == 2#32) then q2 else q3))) j)))

/-- C++: law_q4_word_of -/
def law_q4_word_of (j : U32) : Bool :=
  ((!(BitVec.ult j 32#32)) || ((BitVec.ult (ie_q4_word_of j) 4#32) && (((4#32 * (ie_q4_word_of j)) + (j &&& 3#32)) == (j &&& 15#32))))

/-- C++: law_q4q8_word -/
def law_q4q8_word (wq : U32) (alo : U32) (ahi : U32) : Bool :=
  (((ie_q4q8_word 0#32 wq alo ahi) - (8#32 * ((ie_sum_s8x4 alo) + (ie_sum_s8x4 ahi)))) == (ie_q4q8_word_spec wq alo ahi))

/-- C++: law_q4q8_block -/
def law_q4q8_block (qw : Mem) (qb : U32) (aw : Mem) (ab : U32) : Bool :=
  ((ie_q4q8_block qw qb aw ab (ie_q8_sum aw ab)) == (ie_q4q8_spec 32#32 qw qb aw ab 0#32))

/-- C++: law_q8_addr -/
def law_q8_addr (rows : U32) (nb : U32) (r : U32) (b : U32) (w : U32) (k : U32) : Bool :=
  ((!(((((ie_q8_sizes_ok rows nb) && (BitVec.ult r rows)) && (BitVec.ult b nb)) && (BitVec.ult w 8#32)) && (BitVec.ult k 32#32))) || ((((BitVec.ult (ie_q8_dst_word r b w nb) ((rows * nb) * 8#32)) && (BitVec.ult (ie_q8_dst_scale r b nb) (rows * nb))) && (BitVec.ult (ie_q8_src_qbyte r b k nb) ((rows * nb) * 34#32))) && (BitVec.ult ((ie_q8_src_blk r b nb) + 1#32) ((rows * nb) * 34#32))))

/-- C++: law_q8_inverse -/
def law_q8_inverse (rows : U32) (nb : U32) (r : U32) (b : U32) (w : U32) : Bool :=
  ((!((((ie_q8_sizes_ok rows nb) && (BitVec.ult r rows)) && (BitVec.ult b nb)) && (BitVec.ult w 8#32))) || ((((ie_q8_word_row (ie_q8_dst_word r b w nb) nb) == r) && ((ie_q8_word_blk (ie_q8_dst_word r b w nb) nb) == b)) && ((ie_q8_word_w (ie_q8_dst_word r b w nb)) == w)))

/-- C++: law_q8_onto -/
def law_q8_onto (rows : U32) (nb : U32) (i : U32) : Bool :=
  ((!(((ie_q8_sizes_ok rows nb) && (BitVec.ult 0#32 nb)) && (BitVec.ult i ((rows * nb) * 8#32)))) || (((BitVec.ult (ie_q8_word_row i nb) rows) && (BitVec.ult (ie_q8_word_blk i nb) nb)) && ((ie_q8_dst_word (ie_q8_word_row i nb) (ie_q8_word_blk i nb) (ie_q8_word_w i) nb) == i)))

/-- C++: law_q8_byte -/
def law_q8_byte (q0 : U32) (q1 : U32) (q2 : U32) (q3 : U32) (j : U32) : Bool :=
  ((ie_byte (ie_pack4 q0 q1 q2 q3) (j &&& 3#32)) == ((bif ((j &&& 3#32) == 0#32) then q0 else (bif ((j &&& 3#32) == 1#32) then q1 else (bif ((j &&& 3#32) == 2#32) then q2 else q3))) &&& 255#32))

/-- C++: law_q8q8_block -/
def law_q8q8_block (qw : Mem) (qb : U32) (aw : Mem) (ab : U32) : Bool :=
  ((ie_q8q8_block qw qb aw ab) == (ie_q8q8_spec 32#32 qw qb aw ab 0#32))

/-- C++: law_q4k_addr -/
def law_q4k_addr (rows : U32) (nb : U32) (r : U32) (b : U32) (w : U32) (j : U32) : Bool :=
  ((!(((((ie_q4k_sizes_ok rows nb) && (BitVec.ult r rows)) && (BitVec.ult b nb)) && (BitVec.ult w 4#32)) && (BitVec.ult j 32#32))) || (((((BitVec.ult (ie_q4_dst_word r b w nb) ((rows * nb) * 4#32)) && (BitVec.ult (ie_q4k_sm r b nb) (rows * nb))) && (BitVec.ult ((ie_q4k_dd rows r b nb) + 1#32) (ie_q4k_qs_n rows nb))) && (BitVec.ult ((ie_q4k_src_blk r b nb) + 15#32) ((rows * nb) * 18#32))) && (BitVec.ult (ie_q4k_src_qbyte r b j nb) ((rows * nb) * 18#32))))

/-- C++: law_q4k_inverse -/
def law_q4k_inverse (rows : U32) (nb : U32) (r : U32) (b : U32) (w : U32) : Bool :=
  ((!((((ie_q4k_sizes_ok rows nb) && (BitVec.ult r rows)) && (BitVec.ult b nb)) && (BitVec.ult w 4#32))) || ((((ie_q4_word_row (ie_q4_dst_word r b w nb) nb) == r) && ((ie_q4_word_blk (ie_q4_dst_word r b w nb) nb) == b)) && ((ie_q4_word_w (ie_q4_dst_word r b w nb)) == w)))

/-- C++: law_q4k_onto -/
def law_q4k_onto (rows : U32) (nb : U32) (i : U32) : Bool :=
  ((!(((ie_q4k_sizes_ok rows nb) && (BitVec.ult 0#32 nb)) && (BitVec.ult i ((rows * nb) * 4#32)))) || (((BitVec.ult (ie_q4_word_row i nb) rows) && (BitVec.ult (ie_q4_word_blk i nb) nb)) && ((ie_q4_dst_word (ie_q4_word_row i nb) (ie_q4_word_blk i nb) (ie_q4_word_w i) nb) == i)))

/-- C++: law_q4k_nibble -/
def law_q4k_nibble (l0 : U32) (l1 : U32) (l2 : U32) (l3 : U32) (h0 : U32) (h1 : U32) (h2 : U32) (h3 : U32) (b : U32) (j : U32) : Bool :=
  ((!(BitVec.ult j 32#32)) || ((ie_q4_nib (ie_pack4 (ie_q4k_pack l0 h0 b) (ie_q4k_pack l1 h1 b) (ie_q4k_pack l2 h2 b) (ie_q4k_pack l3 h3 b)) j) == (ie_q4k_src_nib (bif (BitVec.ult j 16#32) then (bif ((j &&& 3#32) == 0#32) then l0 else (bif ((j &&& 3#32) == 1#32) then l1 else (bif ((j &&& 3#32) == 2#32) then l2 else l3))) else (bif ((j &&& 3#32) == 0#32) then h0 else (bif ((j &&& 3#32) == 1#32) then h1 else (bif ((j &&& 3#32) == 2#32) then h2 else h3)))) b)))

/-- C++: law_q4k_dot -/
def law_q4k_dot (qw : Mem) (qb : U32) (aw : Mem) (ab : U32) : Bool :=
  ((ie_q4k_dot qw qb aw ab) == (ie_q4k_spec 32#32 qw qb aw ab 0#32))

end C
