-- Generated by EDG cpfe-lean from the law_ functions in /home/claude/amd-infer/laws/ie_laws.cpp.
-- Do not edit: write the laws in C++ and run the translation again.
-- Each law: for all inputs, the C++ law function returns true.

import IeCore

namespace Laws

/-- C++: law_grid_cover -/
def grid_cover : Prop :=
  forall (rows : C.U32) (r : C.U32),
    C.law_grid_cover rows r = true

/-- C++: law_grid_unique -/
def grid_unique : Prop :=
  forall (g : C.U32) (v : C.U32) (h : C.U32) (w : C.U32),
    C.law_grid_unique g v h w = true

/-- C++: law_lane_cover -/
def lane_cover : Prop :=
  forall (b : C.U32),
    C.law_lane_cover b = true

/-- C++: law_lane_unique -/
def lane_unique : Prop :=
  forall (l : C.U32) (t : C.U32) (m : C.U32) (s : C.U32),
    C.law_lane_unique l t m s = true

/-- C++: law_q4_addr -/
def q4_addr : Prop :=
  forall (rows : C.U32) (nb : C.U32) (r : C.U32) (b : C.U32) (w : C.U32) (k : C.U32),
    C.law_q4_addr rows nb r b w k = true

/-- C++: law_q4_inverse -/
def q4_inverse : Prop :=
  forall (rows : C.U32) (nb : C.U32) (r : C.U32) (b : C.U32) (w : C.U32),
    C.law_q4_inverse rows nb r b w = true

/-- C++: law_q4_onto -/
def q4_onto : Prop :=
  forall (rows : C.U32) (nb : C.U32) (i : C.U32),
    C.law_q4_onto rows nb i = true

/-- C++: law_act_addr -/
def act_addr : Prop :=
  forall (nb : C.U32) (b : C.U32) (v : C.U32),
    C.law_act_addr nb b v = true

/-- C++: law_plan_fits -/
def plan_fits : Prop :=
  forall (p : C.Plan) (i : C.U32) (x : C.U32),
    C.law_plan_fits p i x = true

/-- C++: law_plan_aligned -/
def plan_aligned : Prop :=
  forall (p : C.Plan) (i : C.U32),
    C.law_plan_aligned p i = true

/-- C++: law_plan_no_clobber -/
def plan_no_clobber : Prop :=
  forall (p : C.Plan) (i : C.U32) (j : C.U32) (t : C.U32) (x : C.U32),
    C.law_plan_no_clobber p i j t x = true

/-- C++: law_strided_sum -/
def strided_sum : Prop :=
  forall (x : C.Mem) (nb : C.U32),
    C.law_strided_sum x nb = true

/-- C++: law_wave_sum -/
def wave_sum : Prop :=
  forall (x : C.Mem),
    C.law_wave_sum x = true

/-- C++: law_q4_nibble -/
def q4_nibble : Prop :=
  forall (q0 : C.U32) (q1 : C.U32) (q2 : C.U32) (q3 : C.U32) (j : C.U32),
    C.law_q4_nibble q0 q1 q2 q3 j = true

/-- C++: law_q4_word_of -/
def q4_word_of : Prop :=
  forall (j : C.U32),
    C.law_q4_word_of j = true

/-- C++: law_q4q8_word -/
def q4q8_word : Prop :=
  forall (wq : C.U32) (alo : C.U32) (ahi : C.U32),
    C.law_q4q8_word wq alo ahi = true

/-- C++: law_q4q8_block -/
def q4q8_block : Prop :=
  forall (qw : C.Mem) (qb : C.U32) (aw : C.Mem) (ab : C.U32),
    C.law_q4q8_block qw qb aw ab = true

/-- C++: law_q8_addr -/
def q8_addr : Prop :=
  forall (rows : C.U32) (nb : C.U32) (r : C.U32) (b : C.U32) (w : C.U32) (k : C.U32),
    C.law_q8_addr rows nb r b w k = true

/-- C++: law_q8_inverse -/
def q8_inverse : Prop :=
  forall (rows : C.U32) (nb : C.U32) (r : C.U32) (b : C.U32) (w : C.U32),
    C.law_q8_inverse rows nb r b w = true

/-- C++: law_q8_onto -/
def q8_onto : Prop :=
  forall (rows : C.U32) (nb : C.U32) (i : C.U32),
    C.law_q8_onto rows nb i = true

/-- C++: law_q8_byte -/
def q8_byte : Prop :=
  forall (q0 : C.U32) (q1 : C.U32) (q2 : C.U32) (q3 : C.U32) (j : C.U32),
    C.law_q8_byte q0 q1 q2 q3 j = true

/-- C++: law_q8q8_block -/
def q8q8_block : Prop :=
  forall (qw : C.Mem) (qb : C.U32) (aw : C.Mem) (ab : C.U32),
    C.law_q8q8_block qw qb aw ab = true

end Laws
