#!/usr/bin/env python3
"""Write src/tok_unicode.h: the code point ranges of the Unicode general
categories L (letters), M (marks) and N (numbers), from Python's unicodedata.
The tokenizer (src/tok.c) uses them for \\p{L}, \\p{M}, \\p{N} of the Qwen
pre-tokenizer regex.  Usage: tools/gen_unicode.py > src/tok_unicode.h"""
import sys
import unicodedata

FL, FM, FN = 1, 2, 4


def flag(cp):
    c = unicodedata.category(chr(cp))[0]
    return {"L": FL, "M": FM, "N": FN}.get(c, 0)


ranges = []  # (first, last, flag), flag != 0, adjacent ranges with one flag merged
cur = None
for cp in range(0x110000):
    f = flag(cp)
    if cur and f == cur[2] and cp == cur[1] + 1:
        cur[1] = cp
        continue
    if cur:
        ranges.append(tuple(cur))
    cur = [cp, cp, f] if f else None
if cur:
    ranges.append(tuple(cur))

out = sys.stdout
out.write("/* tok_unicode.h -- generated by tools/gen_unicode.py (Python %s, Unicode %s). Do not edit.\n"
          " * Code point ranges [first, last] of the general categories L (1), M (2), N (4). */\n"
          % (sys.version.split()[0], unicodedata.unidata_version))
out.write("#ifndef IE_TOK_UNICODE_H\n#define IE_TOK_UNICODE_H\n\n#include <stdint.h>\n\n")
out.write("enum { UC_L = 1, UC_M = 2, UC_N = 4 };\n")
out.write("static const uint32_t uc_ranges[][3] = {\n")
for a, b, f in ranges:
    out.write("  {0x%X, 0x%X, %d},\n" % (a, b, f))
out.write("};\n#define UC_NRANGES %d\n\n#endif\n" % len(ranges))
